@startuml
title Diagramme de séquence pour Generate Farm Report
actor Admin
boundary Ecran_Utilisateur
control Controlleur
entity Service_Utilisateur
database Base_de_donnees
collections Cache_Systeme
queue Queue_Operations
entity Système_Externe
Admin_client -> Ecran_Utilisateur: Choisir les critères du rapport
Ecran_Utilisateur -> Controlleur: Envoyer les critères au backend
Controlleur -> Service_Utilisateur: Générer le rapport
Service_Utilisateur -> Base_de_donnees: Rechercher les données nécessaires
Base_de_donnees -> Service_Utilisateur: Fournir les données
Service_Utilisateur -> Controlleur: Envoyer le rapport
Controlleur -> Ecran_Utilisateur: Télécharger ou afficher le rapport
@enduml