@startuml
title Diagramme de séquence pour Generate Farm Report
database Base de données
actor GFW
database Système
boundary Écran
GFW -> Écran: Demander un rapport de ferme
Écran -> Système: Récupérer les données nécessaires
Système -> Base de données: Extraire les données de la ferme
Base de données -> Système: Retourner les données
Système -> Écran: Générer et afficher le rapport
@enduml