"""Add phonenumber and user_type columns to User

Revision ID: 3034ac24370a
Revises: 
Create Date: 2024-06-09 16:04:26.907211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3034ac24370a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subcounty',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('farmergroup_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('geolocation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('farmdata', schema=None) as batch_op:
        batch_op.alter_column('farm_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('crop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('tilled_land_size',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('planting_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('season',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('quality',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('harvest_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('expected_yield',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('actual_yield',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('channel_partner',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('destination_country',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('farmergroup', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('producecategory', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('soildata', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('internal_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('device',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('owner',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nitrogen',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('phosphorus',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('potassium',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('ph',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('humidity',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('conductivity',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('signal_level',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soildata', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('signal_level',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('conductivity',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('humidity',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('ph',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('potassium',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('phosphorus',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('nitrogen',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('owner',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('device',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('internal_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('producecategory', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('farmergroup', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('farmdata', schema=None) as batch_op:
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('destination_country',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('channel_partner',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('actual_yield',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('expected_yield',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('harvest_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('quality',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('season',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('planting_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('tilled_land_size',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('crop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('farm_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.alter_column('geolocation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('farmergroup_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('subcounty',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
